version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
    cooldown:
      default-days: 4
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
    cooldown:
      default-days: 4
    groups:
      notdodo-github:
        dependency-type: "production"
      notdodo-github-dev:
        dependency-type: "development"
