"""Available Licenses"""

from enum import StrEnum


class License(StrEnum):
    """Available Licenses"""

    AFL_3 = "afl-3"
    AGPL_3 = "agpl-3"
    APACHE_2 = "apache-2"
    ARTISTIC_2 = "artistic-2"
    BLUEOAK_1 = "blueoak-1"
    BSD_0 = "0bsd"
    BSD_2_CLAUSE = "bsd-2-clause"
    BSD_2_CLAUSE_PATENT = "bsd-2-clause-patent"
    BSD_3_CLAUSE = "bsd-3-clause"
    BSD_3_CLAUSE_CLEAR = "bsd-3-clause-clear"
    BSD_4_CLAUSE = "bsd-4-clause"
    BSL_1 = "bsl-1"
    CC_BY_4 = "cc-by-4"
    CC_BY_SA_4 = "cc-by-sa-4"
    CC0_1 = "cc0-1"
    CECILL_2 = "cecill-2"
    CERN_OHL_P_2 = "cern-ohl-p-2"
    CERN_OHL_S_2 = "cern-ohl-s-2"
    CERN_OHL_W_2 = "cern-ohl-w-2"
    ECL_2 = "ecl-2"
    EPL_1 = "epl-1"
    EPL_2 = "epl-2"
    EUPL_1 = "eupl-1"
    GFDL_1 = "gfdl-1"
    GPL_2 = "gpl-2"
    GPL_3 = "gpl-3"
    ISC = "isc"
    LGPL_2 = "lgpl-2"
    LGPL_3 = "lgpl-3"
    LPPL_1 = "lppl-1"
    MIT = "mit"
    MIT_0 = "mit-0"
    MPL_2 = "mpl-2"
    MS_PL = "ms-pl"
    MS_RL = "ms-rl"
    MULANPSL_2 = "mulanpsl-2"
    NCSA = "ncsa"
    ODBL_1 = "odbl-1"
    OFL_1 = "ofl-1"
    OSL_3 = "osl-3"
    POSTGRESQL = "postgresql"
    UNLICENSE = "unlicense"
    UPL_1 = "upl-1"
    VIM = "vim"
    WTFPL = "wtfpl"
    ZLIB = "zlib"
