name: Pulumi Preview
on:
  pull_request:

jobs:
  python-ci-pulumi:
    permissions: {}
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0

  pulumi-preview:
    name: Pulumi Preview
    needs: [python-ci-pulumi]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: notdodo/github-actions/.github/workflows/pulumi-preview.yml@pulumi-v0
    with:
      stack-name: notdodo/github
