name: Pulumi Preview
on:
  pull_request:

concurrency:
  group: ghas-github-pulumi-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.8
    with:
      poetry-version: latest
      python-version: 3.13

  preview:
    name: Preview
    needs: python-ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f
        # v4.2.1
        with:
          path: ~/.local
          key: poetry-latest
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        # v5.4.0
        id: install-python
        with:
          python-version: 3.13
          cache: "poetry"
      - run: poetry install
        if: steps.install-python.outputs.cache-hit != 'true'
      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198
        # v1.0.0
        with:
          organization: notdodo
          # kics-scan ignore-line
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:notdodo
      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f
        # v4.2.1
        with:
          path: ~/.pulumi/plugins
          key: python-3.12-pulumi-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            python-3.12-pulumi-
      - uses: pulumi/actions@13b8b7177d6fb736766875dac9b78aab07bd785f
        # v6.0.1
        with:
          always-include-summary: true
          color: always
          command: preview
          comment-on-pr: true
          diff: true
          stack-name: notdodo/github
          suppress-progress: true
