name: Pulumi Up
on:
  push:
    branches:
      - main

concurrency:
  group: ghas-github-pulumi-up-${{ github.ref }}

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.9
    with:
      poetry-version: latest
      python-version: 3.13

  up:
    name: Up
    needs: python-ci
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        # v4.2.2
        with:
          path: ~/.local
          key: poetry-latest
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        # v5.4.0
        id: install-python
        with:
          python-version: 3.13
          cache: "poetry"
      - run: poetry install
        if: steps.install-python.outputs.cache-hit != 'true'
      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198
        # v1.0.0
        with:
          organization: notdodo
          # kics-scan ignore-line
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:notdodo
      - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        # v4.2.2
        with:
          path: ~/.pulumi/plugins
          key: python-3.12-pulumi-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            python-3.12-pulumi-
      - uses: pulumi/actions@3da56e6feff8f5db8b48d3a396bc10ef1f968088
        # v6.1.0
        with:
          command: up
          stack-name: notdodo/github
          color: always
          suppress-progress: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
