name: Pulumi Up
on:
  push:
    branches:
      - main

concurrency:
  group: ghas-github-pulumi-up-${{ github.ref }}

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.14
    with:
      poetry-version: latest
      python-version: 3.13

  up:
    name: Up
    needs: python-ci
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        # v4.2.3
        with:
          path: ~/.local
          key: poetry-latest
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        # v5.6.0
        id: install-python
        with:
          python-version: 3.13
          cache: "poetry"
      - run: poetry install
        if: steps.install-python.outputs.cache-hit != 'true'
      - uses: pulumi/auth-actions@1c89817aab0c66407723cdef72b05266e7376640
        # v1.0.1
        with:
          organization: notdodo
          # kics-scan ignore-line
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:notdodo
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        # v4.2.3
        with:
          path: ~/.pulumi/plugins
          key: python-3.12-pulumi-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            python-3.12-pulumi-
      - uses: pulumi/actions@9519177da243fd32cab35cdbf19cce1ab7472fcc
        # v6.2.0
        with:
          command: up
          stack-name: notdodo/github
          color: always
          suppress-progress: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
