name: Pulumi Preview
on:
  pull_request:

concurrency:
  group: ghas-github-pulumi-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0.0.4
    with:
      poetry-version: latest
      python-version: 3.12

  preview:
    name: Preview
    needs: python-ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        # v5.3.0
        with:
          python-version: 3.12
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        # v4.1.2
        with:
          path: ~/.local
          key: poetry-latest
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - id: cache-deps
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        # v4.1.2
        with:
          path: .venv
          key: python-3.12-poetry-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198
        # v1.0.0
        with:
          organization: notdodo
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:notdodo
      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        # v4.1.2
        with:
          path: ~/.pulumi/plugins
          key: python-3.12-pulumi-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            python-3.12-pulumi-
      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952
        # v6.0.0
        with:
          command: preview
          stack-name: notdodo/github
          comment-on-pr: true
          color: always
          suppress-progress: true
          always-include-summary: true
