name: Pulumi Up
on:
  pull_request:

concurrency:
  group: ghas-github-pulumi-up-${{ github.ref }}

jobs:
  python-ci-pulumi:
    permissions: {}
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0

  pulumi-up:
    name: Pulumi Up
    needs: [python-ci-pulumi]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: notdodo/github-actions/.github/workflows/pulumi-up.yml@pulumi-v0
    with:
      stack-name: notdodo/github
